connection:
  localhost_read:
    host: "127.0.0.1"
    port: 3306
    user: "root"
    password: ~
    database: "db1"
  localhost_write:
    host: "127.0.0.1"
    port: 3306
    user: "root"
    password: ~
    database: "db2"
